# Generated by Django 3.2.5 on 2021-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, to='network.Post'),
        ),
    ]
